Repository Team-with-suhyeon/With-Suhyeon-iOS, pull requests merged in 2025-01, with the labels that each got.

#22 Feature/#19 custom component
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonLongTextField.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonSmallChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonSmallFloatingButton.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Foundation/WithSuyeonChipState.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Modifier/WithSuhyeonModalModifier.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Icons/ic_white_plus.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Icons/ic_white_plus.imageset/ic_white_plus.svg
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Icons/icn_purple_check.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Icons/icn_purple_check.imageset/icn_purple_check.svg
Labels: 👩‍🎤 지원, ➕ add, 🎨 style

#23 Feature/#15 feat components(checkbox, chip, dropdown, floatingButton)
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonCheckbox.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonDropdown.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonMultiSelectBigChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonMultiSelectCheckBigChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonUnderlineButton.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Foundation/WithSuhyeonCheckboxState.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Foundation/WithSuhyeonDropdownState.swift
Labels: 🦹🏻‍♀️ 예지, 🎨 style

#30 Add/#29 add font and fix font style
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Foundation/Font+.swift
Labels: 👩‍🎤 지원, ➕ add

#32 Feature/#26 feat TermsOfService View
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonSmallChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/.gitkeep
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpContent.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpContentCase.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/ActiveAreaView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/PhoneAuthenticationView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/ProfileImageView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/SelectBirthYearView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/SelectGenderView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/TermsOfServiceView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/WriteNickNameView.swift
Labels: 🦹🏻‍♀️ 예지, 🎨 style

#45 Feature/#33 feat authentication nickname view
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/DIContainer+.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/WithSuhyeon_iOSApp.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonMiniButton.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonTextField.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/SignUp/UseCase/ValidateNickNameUseCase.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/PhoneAuthenticationView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/WriteNickNameView.swift
Labels: 🦹🏻‍♀️ 예지, 🎨 style

#58 Feature/#54 blocking account view, start and login view
  WithSuhyeon-iOS/WithSuhyeon-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/WithSuhyeon_iOSApp.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Foundation/WithSuhyeonImage.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_empty.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_empty.imageset/img_empty.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_empty.imageset/img_empty@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_empty.imageset/img_empty@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/Router.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/.gitkeep
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/LoginCompleteView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/LoginFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/LoginView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/.gitkeep
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/BlockingAccountManagement/BlockingAccountManagement.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/BlockingAccountManagement/BlockingAccountManagementFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/MyPageFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/Component/GenderButton.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/PhoneAuthenticationView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Start/StartFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Start/StartView.swift
Labels: 🦹🏻‍♀️ 예지, ✨ feature, 🎨 style

#62 Feature/#61 findsuhyeon detail
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/WithSuhyeon_iOSApp.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/Router.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonDetail/FindSuhyeonDetailFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonDetail/FindSuhyeonDetailView.swift
Labels: 🧛🏻 상욱, 🎨 style

#67 Feature/#64 onboarding api
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/DIContainer+.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/KeyChain/KeyChainManager.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Network/AuthInterceptor.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Network/NetworkManager.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Network/NoAuthInterceptor.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/Router.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Model/Remote/LoginRequestDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Model/Remote/LoginResponseDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Model/Remote/SignUpRequestDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Repository/AuthRepositoryImpl.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Source/Remote/AuthAPI.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Auth/Source/Remote/AuthTarget.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Auth/Entity/Member.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Auth/Repository/AuthRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Auth/UseCase/SignUpUseCase.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Auth/UseCase/ValidateNickNameUseCase.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/LoginFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpFeature.swift
Labels: 🦹🏻‍♀️ 예지, ✨ feature, 🛜 API

#78 Feature/#77 conflict resolve
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonLocationSelect.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Main/MainTabBar.swift
Labels: 🧛🏻 상욱, 🛠️ fix

#79 Feature/#71 blocking account api
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/DIContainer+.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Network/NetworkClient.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Network/NetworkError.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/BlockingAccount/Model/Remote/BlockingAccountRequestDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/BlockingAccount/Model/Remote/BlockingAccountResponseDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/BlockingAccount/Repository/BlockingAccountRepositoryImpl.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/BlockingAccount/Source/Remote/BlockingAccountAPI.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/BlockingAccount/Source/Remote/BlockingAccountTarget.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/BlockingAccount/Entity/BlockingMember.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/BlockingAccount/Repository/BlockingRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/BlockingAccountManagement/BlockingAccountManagement.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/BlockingAccountManagement/BlockingAccountManagementFeature.swift
Labels: 🦹🏻‍♀️ 예지, ✨ feature, 🛜 API

#82 Feature/#76 all connect
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/DIContainer+.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/WithSuhyeon_iOSApp.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonFindSuhyeonDetailContainer.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonMultiSelectCheckBigChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/Router.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/RouterRegistry.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Socket/WebSocketClient.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Chat/Model/Remote/ChatCreateResponseDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Chat/Repository/DefaultChatRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Chat/Source/Remote/ChatSocket.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Chat/Source/Remote/ChatSocketTarget.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/Common/Source/Remote/CommonAPI.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Model/Remote/FindSuhyeonMainRequestDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Model/Remote/FindSuhyeonMainResponseDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Model/Remote/FindSuhyeonPostDetailResponseDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Model/Remote/FindSuhyeonPostRequestDTO.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Repository/DefaultFindSuhyeonRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Source/Remote/FindSuhyeonAPI.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Data/FindSuhyeon/Source/Remote/FindSuhyeonTarget.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Chat/Entity/Create.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/Chat/Repository/ChatRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/FindSuhyeon/Entity/FindSuhyeonMain.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/FindSuhyeon/Entity/FindSuhyeonPost.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/FindSuhyeon/Entity/FindSuhyeonPostDetail.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/FindSuhyeon/Entity/FindSuhyeonPostRequest.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Domain/FindSuhyeon/Repository/FindSuhyeonRepository.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatRoom/ChatRoomFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatRoom/ChatRoomView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonDetail/FindSuhyeonDetailFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonDetail/FindSuhyeonDetailView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Main/MainTabBar.swift
Labels: 🧛🏻 상욱, ✨ feature, 🛜 API

#86 [add] #85 add AppIcon 1024px
  WithSuhyeon-iOS/WithSuhyeon-iOS.xcodeproj/project.pbxproj
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/ic_app1024 1.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/ic_app1024 2.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/ic_app1024.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Info.plist
Labels: 👩‍🎤 지원, ➕ add

#88 [chore] #87 add config file and new appIcon
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/AppIcon.appiconset/ic_app.png
Labels: 👩‍🎤 지원, 👽 chore

#100 [chore] #98 add gender logo
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Component/WithSuhyeonSmallChip.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/Component/FindSuhyeonGenderSelectCell.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonView.swift
Labels: 👩‍🎤 지원, 👽 chore

#107 [fix] chat socket fix
  WithSuhyeon-iOS/WithSuhyeon-iOS/Application/WithSuhyeon_iOSApp.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Router/Router.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/Socket/WebSocketClient.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatRoom/ChatRoomFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatRoom/ChatRoomView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Chat/ChatView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Login/LoginCompleteView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Main/MainTabBar.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Main/MainTabBarFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/MyPage/BlockingAccountManagement/BlockingAccountManagement.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/SignUpView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/MyPost/MyPost.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/SignUp/View/SignUpCompleteView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Splash/SplashView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Start/StartView.swift
Labels: 🧛🏻 상욱, ✨ feature

#112 [Fix] #110 resolve qa issue
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/_Avatar contrast inner border@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/_Avatar contrast inner border@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/img_red_suma.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/img_red_suma@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma.imageset/img_red_suma@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_before.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_before.imageset/btn_profile.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_before.imageset/btn_profile@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_before.imageset/btn_profile@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_before.imageset/img_red_suma.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/Contents.json
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/btn_profile@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/btn_profile@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/img_red_suma_border.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/state=selected, color=red.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/state=selected, color=red@2x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Core/DesignSystem/Resource/Assets.xcassets/Images/img_red_suma_border.imageset/state=selected, color=red@3x.png
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainFeature.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonMain/FindSuhyeonMainView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/FindSuhyeon/FindSuhyeonView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Gallery/GalleryView.swift
  WithSuhyeon-iOS/WithSuhyeon-iOS/Presentation/Main/MainTab.swift
Labels: 👩‍🎤 지원, 🛠️ fix
